version: '3.2'
services:
  # The primary API endpoint service
  paramedics-api:
    image: uwblueprint/paramedics-api
    depends_on:
    - paramedics-db
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
    - "4000:4000"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    env_file:
      - paramedics-web.env
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - /usr/src/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  
  paramedics-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql
      - type: volume
        source: postgresql_data
        target: /var/lib/postgresql/data
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: 100m

volumes:
  postgresql:
  postgresql_data:
