version: '3.7'
services:
  # The primary API endpoint service
  paramedics-api:
    depends_on:
    - paramedics-db
    build:
      context: .
    ports:
    - "8080:8080"
    command:
    - "prod"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
    - PARAMEDICS_DB_HOST=paramedics-db
    - PARAMEDICS_DB_USER=robot
    - PARAMEDICS_DB_PASSWORD=robot_pwd
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - /usr/src/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  
  paramedics-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_DB: paramedics-db
      POSTGRES_USER: robot
      POSTGRES_PASSWORD: robot_pwd
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql
      - type: volume
        source: postgresql_data
        target: /var/lib/postgresql/data
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: 100m

volumes:
  postgresql:
  postgresql_data:
