version: '3.7'
services:
  # The primary API endpoint service
  paramedics-api:
    depends_on:
    - paramedics-db
    build: .
    ports:
    - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
    - PARAMEDICS_DB_HOST=paramedics-db
    - PARAMEDICS_DB_PASSWORD=robot_pwd
    command: [ "node", "server.js" ]
    logging:
      driver: "json-file"
      options:
        max-size: 100m
  
  paramedics-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: robot_pwd
      POSTGRES_USER: robot
      POSTGRES_DB: paramedics-db
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: 100m

volumes:
  postgresql:
  postgresql_data: