version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    docker:
      - image: aaronabraham311/paramedics-web-docker:0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    docker: 
      - image: aaronabraham311/paramedics-web-docker:0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Check if docker is installed
          command: docker -v
      - run:
          name: Building image
          command: docker build -t aaronabraham311/paramedics-web-docker:0.0.2 .
      - run: 
          name: Run Docker compose
          command: |
            set -x
            docker-compose up -d
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
  test:
    docker:
      - image: aaronabraham311/paramedics-web-docker:0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
workflows:
  version: 2
  build-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install