version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    docker:
      - image: aaronabraham311/paramedics-web-docker:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    docker: 
      - image: aaronabraham311/paramedics-web-docker:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Building custom C++ builder for docker
          command: cd ./build/builder/; make optimal; cd ../../
      - run: 
          name: Running build script
          command: ./builder -e rebuild
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
  test:
    docker:
      - image: aaronabraham311/paramedics-web-docker:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
  lint:
    docker:
      - image: aaronabraham311/paramedics-web-docker:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn lint
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
  format:
    docker:
      - image: aaronabraham311/paramedics-web-docker:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn format
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  
workflows:
  version: 2
  dev:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - format:
          requires:
            - install